/**
 * Users API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressStandardClaim } from './addressStandardClaim';


export interface OpenidClaimSet { 
  [key: string]: object | any;


    delegate?: { [key: string]: object; };
    name?: string;
    claims?: { [key: string]: object; };
    nonce?: string;
    issuer?: string;
    subject?: string;
    authenticatedAt?: string;
    authorizedParty?: string;
    accessTokenHash?: string;
    expiresAt?: string;
    issuedAt?: string;
    audience?: Array<string>;
    authenticationContextClass?: string;
    authorizationCodeHash?: string;
    authenticationMethods?: Array<string>;
    address?: AddressStandardClaim;
    locale?: string;
    fullName?: string;
    zoneInfo?: string;
    givenName?: string;
    phoneNumber?: string;
    nickName?: string;
    updatedAt?: string;
    gender?: string;
    emailVerified?: boolean;
    middleName?: string;
    birthdate?: string;
    website?: string;
    familyName?: string;
    picture?: string;
    profile?: string;
    email?: string;
    preferredUsername?: string;
    phoneNumberVerified?: boolean;
    empty?: boolean;
}

